name: Build

on:
    push:
        branches:
            - lovely

jobs:
    build_win:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Deps
              run: |
                  npm config set "//npm.fontawesome.com/:_authToken" "%FA_AUTH_TOKEN%"
                  npm install -g yarn
                  yarn install --verbose
              env:
                  FA_AUTH_TOKEN: ${{ secrets.FA_AUTH_TOKEN }}
            - name: Upload Yarn Errors (on Failure)
              uses: actions/upload-artifact@v1
              if: failure()
              with:
                  name: yarn-error.log
                  path: yarn-error.log
            - name: Build
              run: |
                  yarn make
            - name: Archive production artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: build-win
                  path: build/make/squirrel.windows

    build_mac:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Deps
              run: |
                  npm config set "//npm.fontawesome.com/:_authToken" "${FA_AUTH_TOKEN}"
                  npm install -g yarn
                  yarn install --verbose
              env:
                  FA_AUTH_TOKEN: ${{ secrets.FA_AUTH_TOKEN }}
            - name: Upload Yarn Errors (on Failure)
              uses: actions/upload-artifact@v1
              if: failure()
              with:
                  name: yarn-error.log
                  path: yarn-error.log
            - name: Build
              run: |
                  yarn make
            - name: Archive Build
              uses: actions/upload-artifact@v1
              with:
                  name: build-osx
                  path: build/make
